### ISSUE TITLE
Monophonic glitch

### ISSUE THREAD

**Issue by amsynthdotcom** [asb2m10/dexed#30] opened 2015-02-06 13:20 UTC
Hello!
I noticed today using Dexed in monophonic mode, that if a note is held down and another is played above it, it will correctly move to that note; but if the second note is lower than the held note, there is only silence.  I'm using the current version in KXStudios, 1:20150128-1kxstudio1

Thank you!

brian

**Comment by asb2m10** [comment] 2015-02-10 06:33
I can't reproduce this issue. Is this occuring on all programs (program==preset) or specific programs ?

**Comment by amsynthdotcom** [comment] 2015-02-11 08:26
Hello,
yes, it occurs when monophonic is selected. I'll test out more presets, although all the ones I tried had this issue.

brian

**Comment by MD-78** [comment] 2016-03-19 14:38
I can confirm it (0.9.1 x64).

**Comment by asb2m10** [comment] 2018-02-16 03:02
Closing this issue since I will work with #116 (duplicate)

**Closed by asb2m10** 2018-02-16 03:02 UTC

**Comment by mkruselj** [comment] 2020-02-04 13:29
@asb2m10 This issue has nothing to do with #116 which is a completely different issue.

What @ghost was talking about is that mono mode in Dexed is only high note priority. If you do this:

- hold middle C
- play E above C

it will correctly move to E. But if you do this:

- hold middle C
- play G BELOW that middle C

it won't play anything, it will stay on middle C. So it's not last note priority, which makes it not very useful for many workflows and playing techniques!
