### ISSUE TITLE
[Feature Request] GUI Scaling

### ISSUE THREAD

**Issue by prg318** [asb2m10/dexed#114] opened 2018-01-06 02:59 UTC
It would be great to be able to scale the dexed GUI.  The GUI is very small on a 4K or Hi-DPI display.  I've tried this plugin on both Windows and Linux (through the DISTRHO suite) and both seem to be unscalable.

Would be great to see a usability improvement for HiDPI/4K people

**Comment by a13** [comment] 2018-10-22 22:47
Doesn't Juce support scaling?

**Comment by maverickmarq** [comment] 2018-10-24 00:20
> Doesn't Juce support scaling?

They say they do.  but it's up to developer to implement it. right now all sizes are hardcoded.

JUCE API allows you access to DPI settings for monitors in windows.
So the idea is to at least grab the DPI value and scale it like that.

**Comment by matthieuroche** [comment] 2020-03-30 11:25
+1 for this request!

**Comment by roberChen** [comment] 2020-06-25 09:50
I think it's quite important to support customized dpi setting. By now the plugin seems too small on my computer, I can't read those text on the plugin clearly

**Comment by asb2m10** [comment] 2021-03-07 04:44
Closing this since it is a duplicate of #233. See scaling2x branch for those who are interested.

**Closed by asb2m10** 2021-03-07 04:44 UTC
Labels: enhancement, help wanted
