### ISSUE TITLE
Use Shift for fine tuning

### ISSUE THREAD

**Issue by rickyackel** [asb2m10/dexed#140] opened 2018-05-06 16:09 UTC
Its a niggly thing but I've seen it used on a few other software synths and it is especially useful on Breakpoint, which is probably the least used parameter on the system. When you are getting close to your desired value, holding down shift allows you to move the mouse without overshooting. It would make putting in patches out of books a little easier. 
Gosh, I bet I still have that book that gave you all the parts and patches to do a song. I did Drive by the cars but found patches that were better than the book. Chariots of Fire was in there too.

**Comment by papwalker** [comment] 2018-05-07 16:45
@rickyackel 
Use the MouseWheel.
Shift is married already.

**Comment by rickyackel** [comment] 2018-05-07 20:59
I'm a Trackpad guy, and I've enabled 3 finger Click and drag so my scroll wheel uses 2 finger drag and my normal adjustment 3. I can't tell the difference on most parameters and the Key Velocity is faster with 2 finger than 3. That is likely because the there are only 7 values in Key Velocity. What is Shift married to? Different platforms?

**Comment by rickyackel** [comment] 2018-05-08 18:44
Sorry for the question, I wrote that last one on my phone, or I'd have just looked. That looks like a better use to me too. Does the scroll wheel give you the fine adjustment you like or could it be slower?

**Comment by papwalker** [comment] 2018-05-08 19:04
@rickyackel 
Yes it does. The control advances 1 unit per wheel click. Feedback for instance is seven wheel clicks, breakpoint semitone per click.
I use the wheel 90% of the time with Dexed.
I get really frustrated when going to fancy commercial products and they don't answer to the mousewheel! Should be a law!

**Comment by rickyackel** [comment] 2018-05-08 19:57
I checked Trackpad preferences and there is no way to change the sensitivity of the scrolling. BUT there is a Rotate feature! Having the knob rotate as you rotate two fingers on the trackpad would be surreal. Too much trouble, probably.

**Comment by asb2m10** [comment] 2018-05-11 02:08
Duplicate of #24 ; will work on this one for now on.

**Closed by asb2m10** 2018-05-11 02:08 UTC
