### ISSUE TITLE
VST3: program change message does not notify host about parameter changes

### ISSUE THREAD

**Issue by Spacechild1** [asb2m10/dexed#408] opened 2024-01-09 15:31 UTC
When I change the VST3 program parameter, e.g. in the generic UI of Reaper or with the `[program(` message in the `[vstplugin~]` Pd external, Dexed does not tell which parameters have changed. Other VST3 plugins would call the `restartComponent` method with the `kParamValuesChanged` flag, so that the host can update its own parameter representation.

Tested with Dexed 0.9.6 (VST3) on Windows 10.

**Comment by asb2m10** [comment] 2024-07-10 02:31
There are known issues with VST3 automation with 0.9.6. Please confirm if the issue is still present with the pre-release version.

https://github.com/asb2m10/dexed/releases/tag/v0.9.7pre4

**Comment by asb2m10** [comment] 2024-10-03 02:36
I'm closing this issue since there is no feedback.

**Closed by asb2m10** 2024-10-03 02:36 UTC

**Comment by Spacechild1** [comment] 2024-10-03 05:32
Sorry, I think I missed the GitHub notification! I will test the linked release and reopen in case the issue persists.

Strangely, the parameter *displays* are updated, but the actual values are not! For example, in REAPER's generic UI I can see the actual value in the display, but the sliders remain at the some position. The same thing happens in `[vstplugin~]`.

I'm not sure how this can even happen. With VST3 you typically get the parameter string from the parameter value. I think `IEditController::getParamStringByValue` should be a stateless function. You pass in the parameter ID and the normalized value and you get a string representation of that value. Could it be that Dexed caches the string representation? That would be the only explanation for why the sliders and displays can ever be out of sync.
