### ISSUE TITLE
Sysex messages force pitch bend messages

### ISSUE THREAD

**Issue by papwalker** [asb2m10/dexed#135] opened 2018-04-10 05:52 UTC
Using High Sierra.
If there are any **_Yamaha_** USB keyboards or synths plugged in and active, Dexed 0.9.4 a sound short tone will sound after Key Off or  will generate a continuous tone depending on which host is used. This happens when using any midi source including Dexed Keyboard.
It affects hosts Reaper, AU Lab, Hosting AU using Yamaha KX25, moXF6, moXF and likely others.
It does affect the Dexed stand alone application.
Sometimes changing clock / synch settings on keyboard can help.

NO issues when Midi is restricted to M Audio or other Midi inputs when Yamaha is off or disabled or unpluged.
Tested on 3 different machines. Several Yamaha boards.
DID NOT occur with 0.9.3 version.

Issue Does **NOT** affect Garage Band 10.2.0 or 6.0.5
Issue Does **NOT** affect Live Professor.

It **DOES** affect the Dexed stand alone application.
It **DOES** affect Reaper 5.78
It **DOES** affect AU Lab 2.3
It **DOES** affect Hosting AU 1.5.0

Work around - do not use Yamaha equipment.
No other issues detected.
Other than that - Great job, especially the EG Timing.
Thanks and cheers.
Peter Walker

**Comment by asb2m10** [comment] 2018-04-12 01:45
The Yamaha keyboard is probably sending a sysex that Dexed handles badly. It probably works in Garage Band because it filters the sysex messages.

Can you install https://www.snoize.com/MIDIMonitor/ and try to record the exact midi messages that your Yamaha keyboards sends ?

Then, send me the results (attach files from the issue) and from there I'll be able to fix the issue.

Thanks.

**Comment by papwalker** [comment] 2018-04-12 02:04
Perhaps I wasn't clear enough.
You don't need to actually press keys on a yamaha, pressing keys on the dexed keyboard, or any virtual keyboard or any other keyboard causes this issue. Just having any yamaha plugged in via usb and turned on is enough.
However I will check the midi monitor and send results.
Bear in mind this issue did NOT affect the previous version.

**Comment by papwalker** [comment] 2018-04-12 03:04
There are only Note On and Note Off events in Midi Monitor.
**HOWEVER**
There are **continuous** Midi clock messages in the log.
Setting the Yamaha devices to Clock Off or External Sync resolves the issue.

**All Yamaha synths tested have Sync = Auto and Clock = On as default settings.**
This is a problem as most users would not have a clue about these and altering them just for Dexed is not right especially since the previous version did not require this.
My guess is that anything outputting clock messages will cause issues with Mac Dexed 0.9.4

**Comment by papwalker** [comment] 2018-04-12 03:32
Further to this ...
Windows 7 has the same issue with Dexed and any Yamaha Synths using USB and have the default clock and sync settings. 
Roland Synths have same issue on all platforms.

**Comment by asb2m10** [comment] 2018-04-13 18:33
Thanks for the info, I know what is the issue. Will post a fix shortly.

**Comment by papwalker** [comment] 2018-04-14 02:15
Excellent. Dexed is my all-time favorite plugin for over three years.
Thanks a lot.

**Comment by asb2m10** [comment] 2018-04-24 03:16
Thanks!

I tough I knew what it was but I cannot reproduce it on my side. I think this is really related to #136... I'll keep you posted.

**Comment by nesdnuma** [comment] 2018-04-26 06:46
Hello, I am chiming in this thread as I initiated the issue #136. I didn't have time to send you the requested Reaper session before issue #136 was closed but I can still do it if you want. Using either MIDIberry or Max's sysexin object, I can't see any sysex message coming from my CME XKey keyboard when playing. But if I filter the poly aftertouch messages in Reaper using MIDI Polysher VSTi (http://www.eareckon.com/en/products/freebies.html), the problem disappears.

**Comment by rndrmlch** [comment] 2018-04-26 07:05
changing poly aftertouch to channel aftertouch in the XKey software has done the job for the time being though it's not entirely satisfactory.

**Comment by nesdnuma** [comment] 2018-04-26 07:15
I can't switch to channel aftertouch globally as I do switch live from synths using poly aftertouch and synths which don't. So I filter the messages on Dexed's track but there's obviously an issue with poly aftertouch messages.

**Comment by rndrmlch** [comment] 2018-04-26 07:26
I see. sounds like a viable solution.

**Comment by asb2m10** [comment] 2018-05-03 03:57
Ok good. I'm closing this issue.

**Closed by asb2m10** 2018-05-03 03:57 UTC

**Comment by papwalker** [comment] 2018-05-03 07:31
So the mac is version is no longer supported?

**Comment by asb2m10** [comment] 2018-05-04 03:41
yes

**Comment by papwalker** [comment] 2018-05-04 05:34
@asb2m10
That's a shame, I've only just switched to the Mac, but Dexed is still terrific plugin and I can work around the issues by turning the clock source off.
I realize how hard it is supporting multiple platforms (especially for free)
cheers.

**Comment by asb2m10** [comment] 2018-05-04 12:59
Off course it is supported... just give time to built it and test the built (btw the mac version is updated).

**Comment by nesdnuma** [comment] 2018-05-04 13:30
Thanks for the update. I confirm it functions correctly in Windows now!

**Comment by papwalker** [comment] 2018-05-06 02:36
@asb2m10 
I just built it on the mac this morning, a few implied conversion warnings, but it built and works fine so far with the Yamaha equipment. Confirmed I can see the clock messages on MIDI Monitor.
I'll do a little regression testing but do not expect in trouble.

**Comment by asb2m10** [comment] 2018-05-08 01:48
The KVR builds contains the right version. Just download it again an reinstall it. You should see you are running 0.9.4hf1

**Comment by papwalker** [comment] 2018-05-08 02:05
@asb2m10 
Pascal, he has a Mac. OSX. The Mac install on KVR and GitHub is still March. I just downloaded to be sure, The Windows install is hf1.
Linux version = 404 error

**Comment by asb2m10** [comment] 2018-05-08 02:19
Please try again. And for the Linux version, I need to have access to the it in the comming days.

**Comment by papwalker** [comment] 2018-05-08 02:48
@asb2m10 
@rickyackel 
OK. That's fixed it.
