### ISSUE TITLE
Multiple issues with windows automated build

### ISSUE THREAD

**Issue by siddytucker79** [asb2m10/dexed#230] opened 2020-08-23 21:42 UTC
I'm using Dexed in FL Studio on a Windows PC, and everytime I minimize the plugin window I get an access violation error.  When selecting the plugin from my channel rack I get an "invalid editor window handle" error, and when closing any session with Dexed in it my DAW crashes.  Not sure how to resolve these issues, any help would be much appreciated.
![FL ERROR 1](https://user-images.githubusercontent.com/70114495/90989482-074bf780-e568-11ea-91af-f2b5af746035.png)

**Comment by mkruselj** [comment] 2020-08-24 09:04
Confirmed here in Reaper - closing the plugin GUI crashes host.

**Comment by asb2m10** [comment] 2020-08-25 04:03
I confirm that this is an issue with windows VST3 nightly. I will try to fix this until the end of the week.

**Closed** 2020-09-06 01:44 UTC

**Comment by asb2m10** [comment] 2020-09-06 23:36
I've tested the automated build and the issue seems to be resolved now. Let me know if you still see it on your end.

**Comment by siddytucker79** [comment] 2020-09-07 00:19
Not running into any issues anymore.  Thanks!
