### ISSUE TITLE
Dexed window is too big (Linux)

### ISSUE THREAD

**Issue by hfiguiere** [asb2m10/dexed#239] opened 2020-09-28 03:36 UTC
I'm trying the Dexed VST3 on Linux, on all the hosts I tried, the UI appears scaled like if I was running an HiDPI setup (I disabled a while ago). This cause the Dexed window to be *truncated*.

The previous version didn't have that problem.

See attached screenshot using Ardour (and it's VST3 experimental support) but it's the same in Carla, BitiwigStudio.
![Screenshot from 2020-09-27 23-29-11](https://user-images.githubusercontent.com/114441/94388107-0e8f9380-011a-11eb-86dc-7a84a26e3ebb.png)

**Comment by hfiguiere** [comment] 2020-09-28 21:51
I realize there is a standalone binary, and the same happens with it, so it's cleary not the host fault. In that standalone version the "options" UI isn't scaled up.

**Comment by asb2m10** [comment] 2020-09-30 00:56
I've only test HiDPI detection on Windows and macOS, there is definitely work to do on Linux. Do you have multiple monitors ?

Quick fix for this is to modify the Dexed settings file, make sure the dpiScaleFactor is set to 1.0

```
$ vi ~/.local/share/DigitalSuburban/Dexed/Dexed.xml
<?xml version="1.0" encoding="UTF-8"?>

<PROPERTIES>
  <VALUE name="normalizeDxVelocity" val="0"/>
  <VALUE name="pitchRange" val="3"/>
  <VALUE name="pitchRangeUp" val="3"/>
  <VALUE name="pitchRangeDn" val="3"/>
  <VALUE name="pitchStep" val="0"/>
  <VALUE name="sysexIn" val=""/>
  <VALUE name="sysexOut" val=""/>
  <VALUE name="sysexChl" val="0"/>
  <VALUE name="showKeyboard" val="1"/>
  <VALUE name="wheelMod" val="86 0 0 0"/>
  <VALUE name="footMod" val="0 0 0 0"/>
  <VALUE name="breathMod" val="0 0 0 0"/>
  <VALUE name="aftertouchMod" val="0 0 0 0"/>
  <VALUE name="engineType" val="0"/>
  <VALUE name="dpiScaleFactor" val="1.0"/>
</PROPERTIES>
```

**Comment by hfiguiere** [comment] 2020-09-30 01:36
1. I only have one screen (it's a laptop) and it's configured to be 1600x900 instead of the 3200x1800 (the latter is HiDPI) because of all the usual problems with HiDPI. 0.9.4 always worked fine either way.  If I switch back to HiDPI (3200x1800 with scale 200%), the UI is sized properly, (but the stand alone "options" are way too small to be read).

2. There is no `Dexed.xml` here, if I create it with the content above, indeed, the Dexed UI (standalone) is properly sized. If it is not here, it is never created.

**Comment by moose-und-squirrel** [comment] 2020-10-17 22:55
I have the same scaling issue on macos 10.15.7 (19H2). I'll try creating the Dexed.xml file, since I don't have one in my home directory.

**Comment by redFrik** [comment] 2020-11-09 16:22
This worked for me (macOS Sierra, Dexed 0.9.5)...
Click on the standalone app in Finder, 'get info' (cmd+i) and check 'Open in Low Resolution'.

**Comment by dspasic12** [comment] 2021-01-20 10:49
Hi, i can confirm the GUI issue on Mojave as well 10.14.6
<img width="1440" alt="dexe1" src="https://user-images.githubusercontent.com/52498183/105164528-86445c80-5b15-11eb-981c-8ef30d1c0d9b.png">

**Comment by bigdoghat** [comment] 2021-02-05 10:49
> Hi, i can confirm the GUI issue on Mojave as well 10.14.6
> it's the same for both in low-resolution and without it
> 
Same here in Mojave but found a workaround.  Go into system prefs/displays then click the "scaled" radio button and choose the little window to the right of "default".  This will make it smaller so you can see everything

**Closed** 2021-02-21 02:59 UTC
