### ISSUE TITLE
Some patches not sounding correct until clicking off them and back on them

### ISSUE THREAD

**Issue by KenKennedy** [asb2m10/dexed#42] opened 2015-10-05 15:26 UTC
Obscure set-up, so probably the set-up rather than Dexed, but thought I'd flag as it's only sporadic so could indicate a bug somewhere...
Running Dexed 0.9 on Logic 5.5.1 PC, using Chainer as a VST host - Dexed runs like a dream except when loading a song, some sounds play incorrectly until changed to another patch and then back.
Eg. If patch 4 is selected on a track and sounds strange, selecting patch 5 and then patch 4 again will cure the problem and the patch will sound correctly.

**Comment by asb2m10** [comment] 2016-03-06 05:12
Sorry, but I won't be able to reproduce this issue since it is indeed a obscure setup. 

Unless you can reproduce it in a native setup (native VST on Windows); I will have to close this issue.

**Closed by asb2m10** 2016-03-06 05:12 UTC
