### ISSUE TITLE
After upgrade new version my patches and Dexed are not found on Daw Projects

### ISSUE THREAD

**Issue by STIGMAGOD** [asb2m10/dexed#214] opened 2020-04-13 20:19 UTC
Hi, after i upgrade from version 0.8 to 0.9 my old projects don't recognized the new Dexed
and of course dont charge patches on Ableton
how i can fix this?

Thanx

**Comment by asb2m10** [comment] 2020-04-26 16:10
This is a duplicate of #213.

**Closed by asb2m10** 2020-04-26 16:10 UTC
