### ISSUE TITLE
Poly aftertouch interpreted as pitch bend

### ISSUE THREAD

**Issue by nesdnuma** [asb2m10/dexed#136] opened 2018-04-11 11:44 UTC
Hello,

I've just noticed this issue in Reaper 64-bit: poly aftertouch messages are interpreted as pitch bend messages.

**Comment by rndrmlch** [comment] 2018-04-21 23:15
Hi,

Same problem here on Mac OS with CME 37 XKey.

**Comment by asb2m10** [comment] 2018-04-26 03:06
Found the real issue, it is a duplicate of #135.

**Closed by asb2m10** 2018-04-26 03:06 UTC

**Comment by rickyackel** [comment] 2018-05-05 03:16
I have a Logic Pro X project that shows the issue that I converted to a standard MIDI file? 
[PolyPitchBug.mid.zip](https://github.com/asb2m10/dexed/files/1976291/PolyPitchBug.mid.zip)

**Comment by asb2m10** [comment] 2018-05-05 03:56
With the dexed 0.9.4hf1 version ? (in doubts, click on the dexed logo in the lower left to confirm version)...

**Comment by rickyackel** [comment] 2018-05-05 04:27
Yes Updated March 18, 2018. I have a really cheap keyboard that does poly-pressure that is out of control. you can't even play it without triggering the pressure. The file has me trying to play one note and vary the pressure but it turned out to be two notes because I lifted my finger too much and got a note off. It's a total joke as a keyboard and I end up stripping poly-pressure out of anything I record with it. I've imported that MIDI file into logic and the pitch goes wild.
