### ISSUE TITLE
Notes get stuck when changing patches

### ISSUE THREAD

**Issue by Nintorac** [asb2m10/dexed#220] opened 2020-05-06 23:03 UTC
Hey, great work on this project!! I have come across a minor issue

Steps to reproduce:
- send note on for a key
- change patch
- send note off

Expected: the note off will stop the oscillators
Actual: the note off has no effect and the synth gets stuck in the sustain phase

Workaround: Send midi cc all notes off

**Comment by rickyackel** [comment] 2020-10-08 16:25
I have noticed this when using the side panel list of patches being viewed on disk. When I select a patch in the bottom table of loaded cartridge sounds, it stops the hanging notes. This is easily reproducible when playing a busy part in your DAW while changing patches to see which one works nicely with selected notes. What I was doing was dragging from the side panel to the bottom to save the ones that appeal to me

**Comment by rickyackel** [comment] 2020-10-08 16:27
Note that this part has no Sustain Pedal to cause hanging.

**Comment by beely** [comment] 2020-11-22 22:20
I'd *love* this to be fixed one day - I've always been plagued with stuck notes when using Dexed (Mac AU version, Logic Pro X any version) - and it's the one thing that turns me off using Dexed as it's such a problem here.

The main problem I experience is that when you change patches in the host, any sounding notes (whether held, or still in a longer envelope decay/release stage) are not cut off and continue to sound with the previous sound. This is nice, but it almost always causes hanging/stuck notes from that point, missing note offs and patches/notes that drone on.

In general, I have to try to constantly force kill sounding voices, usually by flipping the mono/poly switch. It makes auditioning patches really quite painful.

I'd be fine if changing patches would hard kill any existing sounding voices if that would mean that notes don't hang, if that's easier to handle internally.

Other than this, it's such a great plugin!

**Comment by mkruselj** [comment] 2021-02-27 22:28
This doesn't seem to happen anymore in the latest nightly when loading patches using the menu or arrows on the main GUI, or bottom area of CART page. HOWEVER, it still happens if you're previewing patches from the cartridge (top right area of CART page). Seems like an easy fix?

**Comment by beely** [comment] 2021-02-27 23:50
Because of your message, I tried the latest nightly build (AU in Logic). Switching patches via the Logic, I'd say the stuck note off behaviour was a little improved (notes tended to not get stuck if they were still sounding in their release phases during a patch change), but would still get stuck more or less consistently if you were holding a note during a patch change.

There was also a new inconsistent host patch loading behaviour - sometimes patches would load in the usual 1 or 2 seconds, other times it would often take up to 10 seconds to load, during which time all graphic activity in Dexed, Logic's meters etc, would freeze.

I'm happy to help test this if people are looking into this behaviour with the goal of getting it fixed.

**Closed** 2021-03-01 04:40 UTC

**Comment by asb2m10** [comment] 2021-03-01 16:10
This should be now fixed including with the cart browser. Let me know if it still doesn't work.

**Comment by beely** [comment] 2021-03-01 18:41
Seems improved, but I still get hanging notes issues in 23ab38b.

I'm running the AU in Logic. When you switch patches via the host (ie, Logic switches to different AUpresets, which are Dexed banks saved as Logic's plugin preset), notes are not terminated on patch change. So if a patch has a long release, and with the notes in their release phase you switch patches, the notes are not terminated and continue to decay until silence. Ok, this is nice.

But if you hold notes in their sustain phase, and use the host to switch patches, again the notes are not terminated, but now when you release the notes, they sustain forever (as we've lost the note offs, and the voices never get to their release stage).

(This doesn't happen when you switch presets just in the plugin - when you change a preset while holding sustained notes, the voices are killed and then the patch change happens).

So really I think the desired behaviour is when the host loads a new plugin preset state, and sounding voices are killed in the process too, to avoid hanging notes.

Thanks for looking at this!

**Comment by asb2m10** [comment] 2021-03-01 21:40
The issue was about AUpresets. Should be fine now with the latest nightly.

**Comment by mkruselj** [comment] 2021-03-06 13:01
I can confirm no more hanging notes over here! Issue can be closed as far as I'm concerned. Thanks for the fix 🙂

**Comment by beely** [comment] 2021-03-06 13:09
Yep, the AU hanging notes on preset change are fixed too. And it's glorious. Thank you!
