### ISSUE TITLE
VST3 0.9.6 crashes in Cubase 13.0.30

### ISSUE THREAD

**Issue by fellowcraft** [asb2m10/dexed#414] opened 2024-03-27 17:12 UTC
Upon exiting Cubase 13.0.30 Dexed VST3 0.9.6 crashed. I'm on Windows 11. Crashdump attached
[Cubase 13.0.30 64bit2024.3.26 22.41.39.463.dmp](https://github.com/asb2m10/dexed/files/14776817/Cubase.13.0.30.64bit2024.3.26.22.41.39.463.dmp)

**Comment by asb2m10** [comment] 2024-07-10 02:31
There are known issues with VST3 automation with 0.9.6. Please confirm if the issue is still present with the pre-release version.

https://github.com/asb2m10/dexed/releases/tag/v0.9.7pre4

**Comment by fellowcraft** [comment] 2024-07-10 19:32
Thanks for addressing it. I get "Virus detected" and can't download. Latest
Chrome and Edge. Latest Windows 11.

**Comment by fellowcraft** [comment] 2024-07-10 19:55
Managed to download via WSL Ubuntu. The ZIP folder only contains a

unzip -l dexed-0.9.7pre4-win.zip
Archive:  dexed-0.9.7pre4-win.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
  5082975  2024-07-09 19:24   dexed-0.9.7pre4.exe.exe
---------                     -------
  5082975                     1 file

**Comment by asb2m10** [comment] 2024-07-10 21:54
Sorry about that, it's the installer that triggers the warning, not the Dexed code. I will see what I can do with it.

I've also added the executable without the installer. This one doesn't trigger any warnings : https://github.com/asb2m10/dexed/releases/download/v0.9.7pre4/dexed-0.9.7pre4-noinstaller-win.zip

**Comment by asb2m10** [comment] 2024-07-10 22:40
I think I've found the problem, Windows doesn't like the compression algo with the installer: https://stackoverflow.com/questions/68834409/program-installed-with-inno-setup-seen-as-trojan-wacatac-bml

I've changed it and now it works; yes the installer is 'bigger' but there is no false positive...

You can test this since I've updated the installer package.

**Comment by fellowcraft** [comment] 2024-07-10 23:06
I downloaded and installed the windows version, no problem. I tested the
VST3 and the CLAP in Bitwig and I can assign remote controllers, no
problem. I prefer the CLAP version. Thanks! Should I test the VST in Cubase?

**Comment by asb2m10** [comment] 2024-07-10 23:11
Great news!

If you can test on Cubase it would be great since I don't have a license.

**Comment by fellowcraft** [comment] 2024-07-11 00:11
VST3, as Cubase does not support CLAP. Works, can assign remote
controllers. However, "Get Default QCs from Plug-In" remains empty and is
not populated with default values. On all other VST synths they are
(pre-)populated with 8 default values.

**Comment by asb2m10** [comment] 2024-07-11 03:53
Thanks, I'll close this and update on the QC stuff with #415

**Closed by asb2m10** 2024-07-11 03:53 UTC
