### ISSUE TITLE
DexED loses patch settings constantly with Cubase 6 and 10.5

### ISSUE THREAD

**Issue by Andyb1580** [asb2m10/dexed#210] opened 2020-03-04 20:04 UTC
After selecting a voice patch DexEd plays ok until the project VCR is used to reastart the track playback.   All patches get reset to the default DexEd patch.

**Comment by asb2m10** [comment] 2020-04-11 04:28
Can you provide a video so I can understand what is going on ?

**Comment by farvardin** [comment] 2020-04-18 08:12
it's the same on Ardour 5.12.0, I'm using the latest Dexed release (from 2018), when I load dexed as LV2 plugin, if I select a patch in a cart and save my work, next time when I reload my work, the same patch is selected, but it doesn't sound correct. 

If I select an other patch, then the previous one, it "resets" the settings and sounds correctly after that. When you have several dexed instruments in a project, it's annoying to reset them after loading the project. 

And if you made some changes in the patch (without saving the patch in a cartridge), the changes are lost. For example if you change the octave (you don't need to create a new instrument for this purpose) 

I made a video, you can see the loaded settings are different from the stored one: https://www.youtube.com/watch?v=f_W96fira1U

**Comment by asb2m10** [comment] 2020-04-26 16:11
I've never released an LV2 plugin. Can you test this with the VST version ?

**Comment by farvardin** [comment] 2020-08-02 09:51
Sorry for the late reply. It seems the problem is only related to the LV2 version. I've made 2 tracks with the same patch, and only the LV2 version has the behavior you can hear in the previous video. Tested on Muse-sequencer and Ardour5.

**Comment by asb2m10** [comment] 2020-09-22 03:01
Closing this since it is only related to the LV2 build.

**Closed by asb2m10** 2020-09-22 03:01 UTC

**Comment by farvardin** [comment] 2020-09-22 12:49
The problem of the OP is probably not with LV2 because he was talking about Cubase, anyway, since he didn't reply we will never know what happened. For me the VST version is working fine :)
